enum ACTION_TYPES {
  FETCH_ALL_MEDIA_DATA_INIT = 'IndexPage@FETCH_ALL_MEDIA_DATA_INIT',
  FETCH_ALL_MEDIA_DATA_SUCCESS = 'IndexPage@FETCH_ALL_MEDIA_DATA_SUCCESS',
  FETCH_ALL_MEDIA_DATA_ERROR = 'IndexPage@FETCH_ALL_MEDIA_DATA_ERROR',
}
export default ACTION_TYPES;
